name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }

    steps:
      - name: Free disk space (aggressive)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          sudo apt-get purge -y 'mongodb-*' 'dotnet-*' 'mysql-*' azure-cli powershell google-chrome-stable firefox microsoft-edge-stable || true
          sudo apt-get autoremove -y && sudo apt-get clean
          sudo swapoff -a || true
          sudo rm -f /swapfile || true
          docker system prune -af --volumes || true

      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build & Push (no local load)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
